# docker-compose.yml
version: '3'
services:
 cms:
    image: cloudmesh/python:latest
    user: $UID:$GID
    volumes:
      - ${HOME}:${HOME}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: $HOME
    stdin_open: true
    tty: true
    command: bash
